### ISSUE TITLE
解析失败了，麻烦修复一下

### ISSUE THREAD

**Issue by GudeSAT** [wzdc/lanzouyunapi#3]
{"code":-1,"msg":"已超时，请刷新","data":{"name":"j72sap1.zip","size":"96.7 M","user":"13**","time":"2023-08-12","desc":"","url":null}}

**Comment by wzdc** [comment]
蓝奏云的JavaScript加了很多注释干扰爬虫，使用手机UA目前还能获取没有密码的文件链接。暂时先用着，我去研究一下

https://api.wzdc.tk/lanzouyunapi?data=https://wwu.lanzouy.com/wzdc&auto=1

https://api.wzdc.tk/lanzouyunapi?data=https://wwu.lanzouy.com/wzdc&mode=mobile

**Comment by GudeSAT** [comment]
好的，谢谢

**Comment by wzdc** [comment]
已修复 https://github.com/wzdc/lanzouyunapi/commit/e381d5b302551a0aa2a8a7d673bf53d9fc6203d2
