### ISSUE TITLE
本地布署返回失败

### ISSUE THREAD

**Issue by lsq** [wzdc/lanzouyunapi#7]
iis + php PHP7.4.1，测试链接`http://localhost/php/lanzouyunapi.php?data=https://www.lanzouo.com/b0ufru1i`
![lanzouapi-2024-08-14_173146](https://github.com/user-attachments/assets/86abd591-fc8b-428d-98f5-c86cf7a9d870)

**Comment by wzdc** [comment]
需要将仓库中的所有php文件都下载下来放到同一文件夹下

**Comment by wzdc** [comment]
还有检查你的网络能不能访问蓝奏云

**Comment by lsq** [comment]
我把全部php放在web服务器根目录下，本地也能访问的蓝奏云，是不是php配置有问题，扩展没有安装还是其他原因，请教下怎么看调试日志

**Comment by wzdc** [comment]
你检查一下你本地的php程序能不能访问到蓝奏云


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月15日(周四) 上午10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wzdc/lanzouyunapi] 本地布署返回失败 (Issue #7)




 
我把全部php放在web服务器根目录下，本地也能访问的蓝奏云，是不是php配置有问题，扩展没有安装还是其他原因，请教下怎么看调试日志
 
&mdash;

**Comment by lsq** [comment]
这个怎么传参，试过php ./lanzouyunapi.php data=https://www.lanzouo.com/b0ufru1i，提示错误

**Comment by wzdc** [comment]
可以通过post或get请求传参。这个与传参无关，如果程序没有获取到就会提示获取失败。
我觉得可能是你没有启用或者安装curl扩展。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月15日(周四) 上午10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wzdc/lanzouyunapi] 本地布署返回失败 (Issue #7)




 
这个怎么传参，试过php ./lanzouyunapi.php data=https://www.lanzouo.com/b0ufru1i，提示错误
 
&mdash;

**Comment by lsq** [comment]
找到原因了， 就是php扩展配置问题；

**Comment by lsq** [comment]
最终经过一个文件一个文件排查是ssl证书没有安装导致的
